application:
  port: 8000
  host: "0.0.0.0"

database:
  require_ssl: true

# En producción, las variables de Upstash se inyectan via env vars:
#   APP_REDIS__UPSTASH_REDIS_REST_URL
#   APP_REDIS__UPSTASH_REDIS_REST_TOKEN
# El config crate las mapea automáticamente al struct RedisSettings.
